Add and configure DDEV
kanopi/drupal-starter pull request #228
Opened 2024-12-29 20:14 UTC by thejimbirch

## Description
Teamwork Ticket(s): [insert_ticket_name_here](insert_link_here)

> As a developer, I need to start with a story.

_A few sentences describing the overall goals of the pull request's commits.
What is the current behavior of the app? What is the updated/expected behavior
with this PR?_

## Acceptance Criteria
* A list describing how the feature should behave
* e.g. Clicking outside a modal will close it
* e.g. Clicking on a new accordion tab will not close open tabs

## Assumptions
* A list of things the code reviewer or project manager should know
* e.g. There is a known Javascript error in the console.log
* e.g. On any `multidev`, the popup plugin breaks.

## Steps to Validate
1. A list of steps to validate
1. Include direct links to test sites (specific nodes, admin screens, etc)
1. Be explicit

## Affected URL
[link_to_relevant_multidev_or_test_site](insert_link_here)

## Deploy Notes
_Notes regarding deployment of the contained body of work. These should note any
new dependencies, new scripts, etc. This should also include work that needs to be 
accomplished post-launch like enabling a plugin._

2025-02-11 16:29 UTC, thejimbirch commented
Needs the following commands:
install-theme-tools
npm
npx
install-critical-tools

Needs configuration:
Solr

2025-03-04 21:55 UTC, thejimbirch commented
README needs to be updated.

2025-05-12 17:28 UTC, echechulina requested changes
@thejimbirch `ddev composer remove kanopi/arbor` returns `Removal failed, kanopi/arbor is still present, it may be required by another package. See `composer why kanopi/arbor`.
Composer [remove kanopi/arbor] failed, composer command failed: exit status 2. stderr=`

2025-05-12 18:23 UTC, kmurphychi247 approved these changes

2025-05-12 18:24 UTC, echechulina approved these changes
Approved

2025-05-12 18:37 UTC, merged